language: node_js

branches:
  only:
    - master

before_install:
- if [[ `node -v` == v0* ]]; then npm i -g npm@3; fi
- if [[ `node -v` != v0* && `npm -v` != 5* ]]; then npm i -g npm@5; fi

node_js:
  - "8"
  - "6"
  - "0.10"
env:
- NODE_TLS_REJECT_UNAUTHORIZED=0
script: "npm run-script test-cover"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
